name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - xexiu
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tomarte el tiempo para completar este reporte de error!
  - type: input
    id: contact
    attributes:
      label: Detalles de Contacto
      description: ¿Cómo podemos ponernos en contacto contigo si necesitamos más información?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Qué sucedió?
      description: Cuéntanos también, ¿qué esperabas que sucediera?
      placeholder: ¡Cuéntanos lo que ves!
      value: "¡Ocurrió un error!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Versión
      description: ¿Qué versión de nuestro software estás utilizando?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
        - Otro (especifíca)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: ¿En qué navegadores estás experimentando el problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Otro (especifíca)
  - type: textarea
    id: logs
    attributes:
      label: Registros relevantes
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conducta
      description: Al enviar este problema, aceptas seguir nuestro [Código de Conducta](https://xexiu.dev/code-conduct/)
      options:
        - label: Acepto seguir el Código de Conducta de este proyecto
          required: true
