name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = development ]; then
          bunx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
          bunx lerna version --conventional-commits --conventional-graduate --yes
        fi

        bunx lerna publish from-git --yes
